# Generated by Django 6.0.6 on 2026-07-04 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('slug', models.SlugField(unique=True, verbose_name='URL标识')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '案例分类',
                'verbose_name_plural': '案例分类',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='案例标题')),
                ('client', models.CharField(max_length=100, verbose_name='客户名称')),
                ('industry', models.CharField(max_length=50, verbose_name='所属行业')),
                ('cover', models.ImageField(upload_to='cases/', verbose_name='案例封面')),
                ('summary', models.TextField(max_length=300, verbose_name='案例简述')),
                ('challenge', models.TextField(blank=True, verbose_name='客户挑战')),
                ('solution', models.TextField(blank=True, verbose_name='解决方案')),
                ('result', models.TextField(blank=True, verbose_name='项目成果')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='首页推荐')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.casecategory', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '成功案例',
                'verbose_name_plural': '成功案例',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
