# Generated by Django 6.0.6 on 2026-07-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=50, verbose_name='联系人')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='公司/品牌')),
                ('project_type', models.CharField(blank=True, choices=[('', '请选择'), ('hotel', '酒店工程'), ('villa', '别墅私宅'), ('commercial', '商业空间'), ('office', '办公家具'), ('realestate', '地产精装'), ('other', '其他')], max_length=20, verbose_name='项目类型')),
                ('quantity', models.CharField(blank=True, choices=[('', '请选择'), ('lt10', '10 件以内'), ('10-50', '10–50 件'), ('50-200', '50–200 件'), ('200-500', '200–500 件'), ('gt500', '500 件以上')], max_length=20, verbose_name='预计数量')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='交付城市')),
                ('budget', models.CharField(blank=True, choices=[('', '请选择'), ('lt5w', '5 万以下'), ('5-20w', '5–20 万'), ('20-50w', '20–50 万'), ('50-100w', '50–100 万'), ('100-500w', '100–500 万'), ('gt500w', '500 万以上')], max_length=20, verbose_name='预算区间')),
                ('message', models.TextField(blank=True, verbose_name='需求说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
            ],
            options={
                'verbose_name': '联系表单',
                'verbose_name_plural': '联系表单',
                'db_table': 'contact',
                'ordering': ['-created_at'],
            },
        ),
    ]
