# Generated by Django 6.0.6 on 2026-07-05 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='budget',
            field=models.CharField(blank=True, max_length=50, verbose_name='预算区间'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='project_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='项目类型'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='quantity',
            field=models.CharField(blank=True, max_length=50, verbose_name='预计数量'),
        ),
    ]
