# Generated by Django 6.0.6 on 2026-07-05 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_contact_budget_alter_contact_project_type_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact',
            table='lianxi',
        ),
    ]
