# Generated by Django 6.0.6 on 2026-07-04 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='公司名称')),
                ('slogan', models.CharField(blank=True, max_length=200, verbose_name='企业口号')),
                ('logo', models.ImageField(blank=True, upload_to='company/', verbose_name='公司Logo')),
                ('favicon', models.ImageField(blank=True, upload_to='company/', verbose_name='网站图标')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('email', models.EmailField(max_length=254, verbose_name='企业邮箱')),
                ('address', models.CharField(max_length=200, verbose_name='公司地址')),
                ('intro', models.TextField(verbose_name='公司简介')),
                ('vision', models.TextField(blank=True, verbose_name='企业愿景')),
                ('mission', models.TextField(blank=True, verbose_name='企业使命')),
                ('values', models.TextField(blank=True, verbose_name='核心价值观')),
                ('qrcode', models.ImageField(blank=True, upload_to='company/', verbose_name='公众号二维码')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '公司信息',
                'verbose_name_plural': '公司信息',
            },
        ),
        migrations.CreateModel(
            name='DevelopmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10, verbose_name='年份')),
                ('title', models.CharField(max_length=100, verbose_name='事件标题')),
                ('description', models.TextField(verbose_name='事件描述')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.companyinfo', verbose_name='所属公司')),
            ],
            options={
                'verbose_name': '发展历程',
                'verbose_name_plural': '发展历程',
                'ordering': ['sort_order', '-year'],
            },
        ),
        migrations.CreateModel(
            name='Honor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='荣誉名称')),
                ('image', models.ImageField(upload_to='honors/', verbose_name='荣誉证书图片')),
                ('description', models.TextField(blank=True, verbose_name='荣誉描述')),
                ('award_date', models.DateField(verbose_name='获奖日期')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.companyinfo', verbose_name='所属公司')),
            ],
            options={
                'verbose_name': '资质荣誉',
                'verbose_name_plural': '资质荣誉',
                'ordering': ['sort_order', '-award_date'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('position', models.CharField(max_length=50, verbose_name='职位')),
                ('avatar', models.ImageField(upload_to='team/', verbose_name='头像')),
                ('intro', models.TextField(blank=True, verbose_name='个人简介')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.companyinfo', verbose_name='所属公司')),
            ],
            options={
                'verbose_name': '团队成员',
                'verbose_name_plural': '团队成员',
                'ordering': ['sort_order'],
            },
        ),
    ]
