"""
Django settings for website project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=p*nw@vfdn5zhkq$td33shk58ouoa^(d!(h50qz28aqz8qoe(d'

# SECURITY WARNING: don't run with debug turned on in production!
_os = __import__('os')

DEBUG = _os.environ.get('DEBUG', 'False').lower() in ('true', '1', 'yes')

# 通过环境变量动态注入域名和主机名
_RENDER_HOST = _os.environ.get('RENDER_EXTERNAL_HOSTNAME')  # Render 自动注入
_CUSTOM_HOST = _os.environ.get('ALLOWED_HOST')

ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    'll54184.eu.cc',
    '.onrender.com',  # Render 默认域名
]
if _RENDER_HOST:
    ALLOWED_HOSTS.append(_RENDER_HOST)
if _CUSTOM_HOST:
    ALLOWED_HOSTS.append(_CUSTOM_HOST)


# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'home.apps.HomeConfig',
    'about.apps.AboutConfig',
    'news.apps.NewsConfig',
    'products.apps.ProductsConfig',
    'cases.apps.CasesConfig',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'website.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'website.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'postgres.eubssgchzdsnownzrwbd',
        'PASSWORD': _os.environ.get('SUPABASE_PASSWORD', 'LLliuleiqwer123'),
        'HOST': 'aws-0-ap-northeast-1.pooler.supabase.com',
        'PORT': '5432',
        'OPTIONS': {
            'sslmode': 'require',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'frontend' / 'dist']

# Whitenoise 压缩 + 缓存
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# CORS 允许前端跨域访问
CORS_ALLOW_ALL_ORIGINS = True

# CSRF 信任来源（允许通过自定义域名登录 admin）
CSRF_TRUSTED_ORIGINS = [
    'https://ll54184.eu.cc',
    'https://new-n8gt.onrender.com',
]

# Django REST Framework 配置
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
}

# SimpleUI 配置
SIMPLEUI_HOME_INFO = False
SIMPLEUI_ANALYSIS = False
SIMPLEUI_DEFAULT_THEME = 'admin.lte.css'
SIMPLEUI_LOGO = '#'
SIMPLEUI_CONFIG = {
    'system_keep': True,
    'menu_display': ['企业概况', '新闻中心', '产品管理', '案例管理', '联系表单', '认证和授权'],
    'dynamic': True,
    'menus': [
        {
            'name': '联系表单',
            'icon': 'fas fa-envelope',
            'models': [
                {
                    'name': '留言管理',
                    'icon': 'fas fa-list',
                    'url': '/admin/home/contact/',
                },
            ],
        },
    ],
}
