# Generated by Django 6.0.6 on 2026-07-04 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('slug', models.SlugField(unique=True, verbose_name='URL标识')),
                ('icon', models.CharField(blank=True, help_text='Font Awesome 图标类名，如 fa-microchip', max_length=50, verbose_name='图标类名')),
                ('description', models.TextField(blank=True, verbose_name='分类描述')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '产品分类',
                'verbose_name_plural': '产品分类',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='产品名称')),
                ('model_number', models.CharField(blank=True, max_length=50, verbose_name='产品型号')),
                ('cover', models.ImageField(upload_to='products/', verbose_name='产品主图')),
                ('summary', models.TextField(max_length=300, verbose_name='产品简介')),
                ('description', models.TextField(verbose_name='详细介绍')),
                ('features', models.TextField(blank=True, help_text='每行一个特点', verbose_name='产品特点')),
                ('specs', models.TextField(blank=True, help_text='每行一个参数，格式：参数名:参数值', verbose_name='规格参数')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='首页推荐')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('online', '已上线'), ('offline', '已下线')], default='online', max_length=10, verbose_name='状态')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productcategory', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '产品服务',
                'verbose_name_plural': '产品服务',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='图片')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='所属产品')),
            ],
            options={
                'verbose_name': '产品轮播图',
                'verbose_name_plural': '产品轮播图',
                'ordering': ['sort_order'],
            },
        ),
    ]
